stages:
  - build

prepare_environment_and_build:
  stage: build
  image: docker:stable
  services:
    - docker:20.10.12-dind
  script:
    # Hack since we are using DinD and can't rely on host path mounts
    - echo "COPY . /src" >> builder.dockerfile
    - docker build -t elastx.se/elx-pba-builder -f builder.dockerfile .
    - docker run --rm elastx.se/elx-pba-builder
  artifacts:
    paths:
      - elx-pba-x86_64.img
    when: always
